---
######################################
## EFS StorageClass
######################################
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
  namespace: airflow
  labels:
    tier: airflow
    component: efs-sc
provisioner: efs.csi.aws.com
