---
############################################
## Airflow ESO SecretStore
############################################
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: airflow-eso-secretstore
  namespace: airflow
  labels:
    tier: airflow
    component: secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: airflow-eso-serviceaccount
