---
############################################
## Airflow ESO
############################################
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-secret
  namespace: airflow
  labels:
    tier: airflow
    component: secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: airflow-eso-secretstore
    kind: SecretStore
  target:
    name: airflow-secret
    creationPolicy: Owner
  data:
    - secretKey: AIRFLOW__CORE__FERNET_KEY
      remoteRef:
        key: ansible/airflow_secrets
        property: airflow_fernet_key
        version: "AWSCURRENT"
    - secretKey: AIRFLOW__WEBSERVER__SECRET_KEY
      remoteRef:
        key: ansible/airflow_secrets
        property: airflow_webserver_key
        version: "AWSCURRENT"
    - secretKey: _AIRFLOW_WWW_USER_USERNAME
      remoteRef:
        key: ansible/airflow_secrets
        property: airflow_username
        version: "AWSCURRENT"
    - secretKey: _AIRFLOW_WWW_USER_PASSWORD
      remoteRef:
        key: ansible/airflow_secrets
        property: airflow_password
        version: "AWSCURRENT"
    - secretKey: AIRFLOW__SMTP__SMTP_USER
      remoteRef:
        key: ansible/airflow_secrets
        property: airflow_smtp_user
        version: "AWSCURRENT"
    - secretKey: AIRFLOW__SMTP__SMTP_PASSWORD
      remoteRef:
        key: ansible/airflow_secrets
        property: airflow_smtp_pass
        version: "AWSCURRENT"