---
- name: Ensure required packages are installed
  ansible.builtin.pip:
    name:
      - alembic[tz]
      - psycopg2-binary
    state: present
  become: true

- name: Create PostgreSQL databases
  community.postgresql.postgresql_db:
    name: "{{ deployment_env }}.{{ db_name_prefix }}"
    login_host: "{{ rds_endpoint }}"
    login_user: "{{ db_root_user }}"
    login_password: "{{ db_root_password }}"
    state: present
  become: true

- name: Create Read/Write user
  community.postgresql.postgresql_user:
    db: "{{ deployment_env }}.{{ db_name_prefix }}"
    name: "{{ db_rw_user }}"
    password: "{{ db_rw_password }}"
    role_attr_flags: "CREATEDB,LOGIN"
    login_host: "{{ rds_endpoint }}"
    login_user: "{{ db_root_user }}"
    login_password: "{{ db_root_password }}"
    state: present
  become: true

- name: Create Read-Only user
  community.postgresql.postgresql_user:
    db: "{{ deployment_env }}.{{ db_name_prefix }}"
    name: "{{ db_ro_user }}"
    password: "{{ db_ro_password }}"
    role_attr_flags: "LOGIN"
    login_host: "{{ rds_endpoint }}"
    login_user: "{{ db_root_user }}"
    login_password: "{{ db_root_password }}"
    state: present
  become: true
