version: '3.8'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    networks:
      - my_network

  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - my_network

  redis:
    image: redis
    ports:
      - "6378:6379"  # Change the host port to 6378
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mongodb_data:
