version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'

  client:
    build: client
    volumes: 
      - ./client:/rpc_client
    environment:
      - PYTHONUNBUFFERED=1

  server:
    build: server
    volumes:
      - ./server:/rpc_server
    environment:
      - '5001:5001'
