---
################################
## Airflow Webserver Service
#################################
apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    tier: airflow
    component: webserver
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    tier: airflow
    component: webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
