version: '3.5'

services:
  udp-chat-server:
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - "9999:9999/udp"
  
  udp-chat-client:
    build:
      dockerfile: ./client/Dockerfile
    