- name: Create user group for the user (each user has their separate isolated group)
  group:
    name: "{{ os_username }}"
    state: present

- name: Ensure directory to store passwords exists 
  file:
    path: "{{ password_directory }}"
    state: directory

- name: Create user account
  user:
    group: "{{ os_username }}"
    groups: docker # temporary solution
    name: "{{ os_username }}"
    shell: /bin/bash
    append: yes
    home: "{{ home_dir }}"
    password: "{{ lookup('password', password_file_path) | password_hash('sha512') }}"

- name: Add user's pub key to his authorized_keys
  authorized_key:
    user: "{{ os_username }}"
    key: "{{ lookup('file', pub_key_path) }}"
    state: present

- name: Save server IP to a file
  local_action:
    module: lineinfile
    path: "{{ server_ip_file_path }}"
    line: "{{ ansible_default_ipv4.address }}"
    create: yes
