- name: Create user group for the user (each user has their separate isolated group)
  group:
    name: "{{ os_username }}"
    state: present

- name: Ensure directory to store passwords exists 
  file:
    path: "{{ password_directory }}"
    state: directory
    
- name: Setup permissions on user's home directory
  file:
    path: "{{ home_dir }}"
    state: directory
    mode: 0700
    
- name: Create user account
  user:
    group: "{{ os_username }}"
    groups: docker # temporary solution
    name: "{{ os_username }}"
    shell: /bin/bash
    append: yes
    home: "{{ home_dir }}"
    password: "{{ lookup('password', password_file_path) | password_hash('sha512') }}"

- name: Add user's pub key to his authorized_keys
  authorized_key:
    user: "{{ os_username }}"
    key: "{{ lookup('file', pub_key_path) }}"
    state: present

- name: Save server IPs to a file
  run_once: true
  local_action:
    module: lineinfile
    path: "{{ server_ip_file_path }}"
    line: "{{ groups['all'] | map('extract', hostvars, ['ansible_default_ipv4', 'address']) | join('\n') }}"
    create: yes
