---
- name: Restart Zabbix Server
  ansible.builtin.systemd:
    name: zabbix-server
    state: restarted
  become: true

- name: Restart Apache
  ansible.builtin.systemd:
    name: apache2
    state: restarted
  become: true

- name: Restart MySQL
  ansible.builtin.systemd:
    name: mysql
    state: restarted
  become: true

- name: Restart Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent2
    state: restarted
  become: true
