---
- name: Ansible | Include variables containing secrets
  no_log: true
  include_vars:
    file: secrets.yml

- name: Ansible | Set CA password for EU instance
  set_fact:
    easyrsa_ca_password: "{{ easyrsa_ca_password_vpn1_eu }}"
  when: vpn_region == "eu"    
    
- name: Ansible | Include variables for VPN1 server in EU
  include_vars:
    file: vpn1-eu.yml
  when: vpn_region == "eu"  

- name: Ansible | Set CA password for US instance
  set_fact:
    easyrsa_ca_password: "{{ easyrsa_ca_password_vpn1_us }}"
  when: vpn_region == "us"
  
- name: Ansible | Include variables for VPN1 server in US
  include_vars:
    file: vpn1-us.yml
  when: vpn_region == "us" 

- name: OpenVPN | Revoke Client | Revoke access
  expect:
    command: "./easyrsa revoke {{ openvpn_client_username }}@{{ openvpn_server_common_name }}"
    responses:
      'Enter pass phrase for .*?:$': "{{ easyrsa_ca_password }}"
    chdir: "{{ easyrsa_dir }}"
  no_log: false

- name: OpenVPN | Revoke Client | Rebuild CRL
  expect:
    command: ./easyrsa gen-crl
    responses:
      'Enter pass phrase for .*?:$': "{{ easyrsa_ca_password }}"
    chdir: "{{ easyrsa_dir }}"
  no_log: false

- name: OpenVPN | Google Authenticator | Remove MFA user from OS
  user:
    name: "{{ openvpn_client_username }}"
    state: absent
    remove: yes
#  notify: Restart openvpn

- name: OpenVPN | Google Authenticator | Remove MFA user seed
  file:
    path: "{{ gauth_dir }}/{{ openvpn_client_username }}"
    state: absent