[tool.poetry]
name = "im"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
pandas = "^1.2.0"
psycopg2-binary = "*"
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
