[tool.poetry]
name = "amp_opt"
version = "1.0.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
# This doesn't install (see Amp issue 1836).
#cvxpy = "*"
flaky = "*"
invoke = "*"
jsonpickle = "*"
jupyter = "*"
jupyter_contrib_nbextensions = "*"
jupyter_nbextensions_configurator = "*"
jupytext = "*"
matplotlib = "*"
pandas = "^1.2.0"
pyarrow = "*"
pygraphviz = "*"
pytest = "^6.0.0"
pytest-cov = "*"
pytest-instafail = "*"
pytest-xdist = "*"
python = "^3.9"
requests = "*"
s3fs = "*"
seaborn = "*"
sklearn = "*"
statsmodels = "*"
tqdm = "*"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
