---
################################
## Airflow Pod Launcher RoleBinding
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-launcher-rolebinding
  namespace: airflow
  labels:
    tier: airflow
    component: pod-launcher-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-launcher-role
subjects:
  - kind: ServiceAccount
    name: airflow-scheduler
    namespace: airflow
