---
################################
## Airflow Pod Launcher Role
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-launcher-role
  namespace: airflow
  labels:
    tier: airflow
    component: pod-launcher-role
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/log"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - "create"
      - "list"
      - "get"
      - "patch"
      - "watch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "list"
