---
################################
## Airflow Pod Reader Role Binding
#################################
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-log-reader-rolebinding
  namespace: airflow
  labels:
    tier: airflow
    component: pod-log-reader-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-log-reader-role
subjects:
  - kind: ServiceAccount
    name: airflow-webserver
    namespace: airflow
