---
######################################
## Airflow Webserver ServiceAccount
######################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: airflow-webserver
  namespace: airflow
  labels:
    tier: airflow
    component: webserver
