- name: Create user on VPN and DEV
  hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: roles/vpn_user_add }
    - { role: roles/server_user_add }
    - { role: roles/vnc_user_add }

#ansible-playbook plays/all_user_add.yml --user ubuntu --private-key=/root/.ssh/id_rsa_crypto --inventory 13.48.137.208, --extra-vars "openvpn_client_username= openvpn_client_password= openvpn_client_pem_passphrase=" --ask-vault-pass