- hosts: all
  become: yes
  roles:
    - role: roles/server_configure_os

# ansible-playbook plays/server_configure_os.yml --user ubuntu --private-key=/root/.ssh/id_rsa_crypto --inventory 172.30.2.136, --extra-vars "disk_configuration_enabled=false"