- name: Remove VPN user from openvpn server
  hosts: 172.30.1.125
  become: true
  gather_facts: true
  roles:
    - { role: roles/vpn_user_remove }
    
#ansible-playbook plays/vpn_user_remove.yml --user ubuntu --private-key=/root/.ssh/id_rsa_crypto --inventory 172.30.1.125, --extra-vars "openvpn_client_username=" --ask-vault-pass