- name: Create VPN user on openvpn server
  hosts: 13.51.59.43
  become: true
  gather_facts: true
  roles:
    - { role: roles/vpn_user_add }

#ansible-playbook plays/vpn_user_add.yml --user ubuntu --private-key=/root/.ssh/id_rsa_crypto --inventory 13.51.59.43, --extra-vars "openvpn_client_username= openvpn_client_password= openvpn_client_pem_passphrase=" --ask-vault-pass