version: '3'

services:
  # Docker container running code that talks to the DB.
  app:
    # TODO(Grisha): Use image env var.
    # TODO(Grisha): for image name use `get_docker_base_image_name`() from `repo_config.py`.
    image: 665840871993.dkr.ecr.us-east-1.amazonaws.com/cmamp:dev
    environment:
      - ENV_NAME=venv
    restart: "no"
    depends_on:
      - im_postgres_local
    volumes:
      - ../../../:/app
      - ~/.aws:/home/.aws
    env_file:
      - ../env/local.im_db_config.env
    working_dir: /app
    entrypoint: /app/devops/docker_run/entrypoint.sh

  # Docker container running Postgres DB.
  im_postgres_local:
    image: postgres:13
    restart: "no"
    volumes:
      - im_postgres_data_local:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ../env/local.im_db_config.env

volumes:
  im_postgres_data_local: {}
