version: '3'

services:
  # Docker container running code that talks to the DB.
  app:
    # TODO(Grisha): use environment variable for image.
    image: 665840871993.dkr.ecr.us-east-1.amazonaws.com/amp:dev
    depends_on:
      - im_postgres
    restart: "no"
    volumes:
      - ../../../:/app
      - ~/.aws:/app/home/.aws
    working_dir: /app
    entrypoint: /app/devops/docker_build/entrypoint.sh

  # Docker container running Postgres DB.
  im_postgres:
    image: postgres:13
    restart: "no"
