- name: Ensure project folder exists
  file:
    path: "{{ airflow_project_folder }}"
    state: directory

- name: Ensure directory for custom DAGs
  file:
    path: /opt/bitnami/airflow/dags
    state: directory

- name: Ensure directory for additional python requirements
  file:
    path: /bitnami/python/requirements.txt
    state: directory

- name: Fetch docker-compose file
  get_url:
    url: "{{ airflow_compose_url }}"
    dest: "{{ airflow_project_folder }}/docker-compose.yml"

- name: Add .env file for airflow
  template:
    src: .env.j2
    dest: "{{ airflow_project_folder }}/.env"

- name: test source profile
  shell: echo $TMPDIR
  register: output

- debug:
    msg: "Output: {{ output.stdout_lines }}"

- name: Start airflow viac docker-compose in detached mode
  shell: /bin/bash -ilc "docker-compose -f '{{ airflow_project_folder }}'/docker-compose.yml up -d"
  # -lc needed to load .bashrc and .profile and execute command set as string parameter

