zabbix_package_url: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu/pool/main/z/zabbix-release/zabbix-release_{{ zabbix_version }}-1+ubuntu20.04_all.deb"

# Using the 'ck' profile to access AWS Secrets Manager
profile: "ck"

# Fetching the secret
airflow_secrets: "{{ lookup('amazon.aws.secretsmanager_secret', 'ansible/airflow_secrets', region='eu-north-1', aws_profile=profile) }}"

zabbix_db_user: "{{ airflow_secrets.zabbix_db_user }}"
zabbix_db_password: "{{ airflow_secrets.zabbix_db_password }}"
mysql_db_user: "{{ airflow_secrets.mysql_db_user }}"
mysql_db_password: "{{ airflow_secrets.mysql_db_password }}"
