---
################################
## Cluster AutoScaler ServiceAccount
#################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler-serviceaccount
  namespace: kube-system
  labels:
    k8s-addon: cluster-autoscaler.addons.k8s.io
    k8s-app: cluster-autoscaler
