---
server_user_action: 'add' # can be 'add' or 'remove'
os_include_user_home_directory: false

os_username:
os_password:
home_dir: /data/{{ os_username }}
pub_key_path: "/opt/crypto_vpn/{{ os_username }}/user_credentials/crypto.pub"

# Password Management
password_directory: "/opt/crypto_vpn/{{ os_username }}/user_credentials"
password_file_path: "{{ password_directory }}/os_password.txt"

# Set path to file to containing server ip
server_ip_file_path: "{{ password_directory }}/server_ip.txt"
