version: '3'

services:
  gremlin:
    image: tinkerpop/gremlin-server
    ports:
      - "8182:8182"
    volumes:
      - ./gremlin-server.yaml:/opt/gremlin-server/conf/gremlin-server.yaml

  gremlin-python:
    build:
      context: .
    depends_on:
      - gremlin
