version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    networks:
      - mysql-network

  flask_app:
    build:
      context: .
      dockerfile: restfulapi_flask.dockerfile
    container_name: flask-app-container
    ports:
      - "8888:8888"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: your_password
      DB_NAME: employees
    networks:
      - mysql-network
    volumes:
      - ./app:/app

networks:
  mysql-network:
    driver: bridge
