version: '3.8'

services:
  neo4j:
    container_name: neo4j-server
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4JAUTH=NONE"
    networks:
      - graph-net
    volumes:
      - ./neo4j/data:/app/data
 
  spark:
    build: .
    ports:
      - "8080:8888"
    networks:
      - graph-net


networks:
  graph-net:
