---
- name: update facts
  setup: ~
  tags:
    - fact

- name: import docker gpg key
  become: 'yes'
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg"
    state: present
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - docker

- name: apt docker.list
  become: 'yes'
  template:
    src: docker.repo.j2
    dest: /etc/apt/sources.list.d/docker.list
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - docker

- name: apt update
  become: 'yes'
  apt:
    update_cache: 'yes'
  when: ansible_os_family == "Debian"
  tags:
    - apt

- name: stat docker-ce.repo file
  stat:
    path: "/etc/yum.repos.d/docker-ce.repo"
  register: docker_ce_repo

- name: docker yum repo
  become: 'yes'
  command: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  when: ansible_os_family == "RedHat" and not docker_ce_repo.stat.exists
  tags:
    - dnf

- name: install docker
  become: 'yes'
  package:
    name: ['docker-ce', 'docker-ce-rootless-extras']
    state: present
  tags:
    - apt
    - dnf
    - docker
...
