---
- name: Get UID of user to calculate dektop number to assign
  shell: id -u "{{ vnc_user }}"
  register: user_uid

- debug:
    msg: "User UID is: {{ user_uid.stdout }}"

# Desktop number go from 1,2 etc. UIDs start from 1000
- set_fact:
    vnc_desktop_number: "{{ user_uid.stdout | int - 999 }}"

- name: Disable and stop VNC service
  systemd:
    name: "{{ vnc_user }}_vncserver@{{ vnc_desktop_number }}"
    state: stopped
    enabled: false

- name: Remove systemd entry for user's vnc service
  file:
    path: "/etc/systemd/system/{{ vnc_user }}_vncserver@.service"
    state: absent
    
- name: Systemd to reread configs
  systemd:
    daemon_reload: yes